/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("su.nexmedia.java-conventions")
}

dependencies {
    compileOnly(project(":NexEngine"))
    compileOnly("io.papermc.paper:paper-api:1.19.3-R0.1-SNAPSHOT")
    compileOnly("io.netty:netty-all:4.1.85.Final")
    compileOnly("it.unimi.dsi:fastutil:8.5.11")
}

description = "PlayerBlockTracker"

java {
    withSourcesJar()
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}