/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "NexEnginePlugin"

include(":NexEngineAPI")

// The Paper plugin
include(":NexEngine")

// Code related to random 3rd party plugins
include(":NexEngineExt")

include(":NMS")
include(":NexEngineCompat_V1_19_R1")
include(":NexEngineCompat_V1_19_R2")
include(":NexEngineCompat_V1_17_R1")
include(":NexEngineCompat_V1_18_R2")

// include(":PlayerBlockTracker") // TODO make it a separate module

pluginManagement {
    repositories {
        gradlePluginPortal()
        maven("https://papermc.io/repo/repository/maven-public/")
    }
}