/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("su.nexmedia.java-conventions")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.19.3-R0.1-SNAPSHOT")
}

description = "NexEngineAPI"

java {
    withSourcesJar()
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}