/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("su.nexmedia.java-conventions")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT")
    compileOnly("io.netty:netty-all:4.1.85.Final")
}

description = "NMS"
