/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("su.nexmedia.java-conventions")
    id("io.papermc.paperweight.userdev")
}

dependencies {
    compileOnly(project(":NMS"))
    paperDevBundle("1.19.2-R0.1-SNAPSHOT")
}

description = "NexEngineCompat_V1_19_R1"

tasks {
    assemble {
        dependsOn(reobfJar)
    }
}
